=== clarin-eric/VirtualCollectionRegistry/serialization/src/main/validation/VirtualCollection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified">

  <xs:element name="VirtualCollections">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="VirtualCollection" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="totalCount" type="xs:integer"/>
      <xs:attribute name="offset" type="xs:integer"/>
      <xs:attribute name="result">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="full"/>
            <xs:enumeration value="partial"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="VirtualCollection">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="extensional"/>
              <xs:enumeration value="intensional"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="Description" type="xs:string" minOccurs="0"/>
        <xs:element name="CreationDate" type="xs:date" minOccurs="0"/>
        <xs:element name="ModificationDate" type="xs:date" minOccurs="0"/>
        <xs:element name="PublicationDate" type="xs:date" minOccurs="0"/>
        <xs:element name="Creators" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Creator" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                      <xs:element name="FamilyName" type="xs:string"/>
                      <xs:element name="GivenName" type="xs:string"/>
                      <xs:element name="Address" type="xs:string" minOccurs="0"/>
                      <xs:element name="Email" type="xs:string" minOccurs="0"/>
                      <xs:element name="Organisation" type="xs:string" minOccurs="0"/>
                      <xs:element name="Telephone" type="xs:string" minOccurs="0" />
                      <xs:element name="Website" type="xs:anyURI" minOccurs="0" />
                      <xs:element name="Role" type="xs:string" minOccurs="0" />
                    </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Purpose" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="research"/>
              <xs:enumeration value="reference"/>
              <xs:enumeration value="sample"/>
              <xs:enumeration value="future-use"/>
              <!-- to be extended -->
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Reproducibility" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="intended"/>
              <xs:enumeration value="fluctuating"/>
              <xs:enumeration value="untended"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="ReproducibilityNotice" type="xs:string" minOccurs="0" />
        <xs:element name="Keywords" minOccurs="0">
          <xs:complexType>
        	<xs:sequence>
        	  <xs:element name="Keyword" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        	</xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Resources" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Resource" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ResourceType">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Metadata"/>
                          <xs:enumeration value="Resource"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="ResourceRef">
                      <xs:simpleType>
                        <xs:restriction base="xs:anyURI"/>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Label" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Description" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="GeneratedBy" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Description" type="xs:string"/>
              <xs:element name="URI" type="xs:anyURI" minOccurs="0"/>
              <xs:element name="Query" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="profile" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:long" use="optional" />
      <xs:attribute name="persistentId" type="xs:string" use="optional" />
      <xs:attribute name="state" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="private" />
            <xs:enumeration value="public_pending" />
            <xs:enumeration value="public" />
            <xs:enumeration value="public_frozen_pending" />
            <xs:enumeration value="public_frozen" />
            <xs:enumeration value="deleted" />
            <xs:enumeration value="dead" />
            <xs:enumeration value="error" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== clarin-eric/VirtualCollectionRegistry/VirtualCollectionRegistry/src/test/resources/VirtualCollection-intensional.xml
<?xml version="1.0" encoding="UTF-8"?>
<VirtualCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="VirtualCollection.xsd">
    <Type>intensional</Type>
    <Name>Test Collection 2</Name>
    <Description>Test Description</Description>
    <CreationDate>2009-12-31</CreationDate>
    <Creators>
        <Creator>
            <Person>Joe User</Person>
            <Email>joe.user@example.com</Email>
            <Organisation>Example Organization</Organisation>
        </Creator>
    </Creators>
    <Purpose>sample</Purpose>
    <Reproducibility>untended</Reproducibility>
    <ReproducibilityNotice>Unmaintaned test collection.</ReproducibilityNotice>
    <Keywords>
        <Keyword>test</Keyword>
        <Keyword>unmaintained</Keyword>
    </Keywords>
    <GeneratedBy>
        <Description>GeneratedBy description</Description>
        <URI>urn:x-vcr:test-uri</URI>
        <Query profile="sql"><![CDATA[<SQL>Test-Query</SQL>]]></Query>
    </GeneratedBy>
</VirtualCollection>
